version: '2'
services:
  web:
    build: .
    image: scta-rdf
    command: bin2/scta-rdf start_fuseki build-v4.3.1
    volumes:
      - ../scta-rdf-builds/build:/home/scta-rdf/build
      - ../scta-rdf-builds/fuseki-builds:/home/scta-rdf/fuseki-builds
      - ../scta-rdf-builds/logs:/home/scta-rdf/logs
    ports:
      - "3030:3030"