version: '2'
services:
  web:
    build: .
    image: scta-rdf
    command: bin2/scta-rdf start_fuseki build
    volumes:
      - ./build:/home/scta-rdf/build
      - ./fuseki-builds:/home/scta-rdf/fuseki-builds
      - ./logs:/home/scta-rdf/logs
    ports:
      - "3000:3000"
